/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * Copyright (c) 2022 STMicroelectronics.
 * All rights reserved.
 *
 * This software is licensed under terms that can be found in the LICENSE file
 * in the root directory of this software component.
 * If no LICENSE file comes with this software, it is provided AS-IS.
 *
 ******************************************************************************
 */


#include <stdint.h>

uint32_t wait_millisecond = 1000;
uint32_t wait_counter = 0;

#define RCC_AHB2ENR  *((volatile uint32_t*)( 0X40021000 + 0x04C))
#define LED1_MODER *((volatile uint32_t*)( 0x42020400))
#define LED2_MODER *((volatile uint32_t*)( 0x42020800))
#define PUSHBUTTON_MODER *((volatile uint32_t*)( 0x42020800))
#define LED1_ODR *((volatile uint32_t*)( 0x42020414))
#define LED2_ODR *((volatile uint32_t*)( 0x42020814))
#define PUSHBUTTON_IDR *((volatile uint32_t*)( 0x42020810))


int main(void) {

	RCC_AHB2ENR |= 1<<1;
	RCC_AHB2ENR |= 1<<2;
	LED1_MODER  &= ~(0x01 << 15);
	LED2_MODER  &= ~(0x01 << 15);
	PUSHBUTTON_MODER  &= ~(0x01 << 27);
	PUSHBUTTON_MODER  &= ~(0x01 << 26);

	while(1) {
		volatile int index;

		LED1_MODER |= (0x01 << 7);

		while(PUSHBUTTON_IDR & (0x01 << 13)){

		LED1_MODER &= ~(0x01 << 7);
		LED2_MODER |= (0x01 << 7);
		}

		LED2_MODER &= ~(0x01 << 7);

		for(index=0;index<wait_millisecond*333;index++);
		wait_counter = wait_counter + 1;
		}
	}










